/**
 * SPARK_DASH_DESKTOP_VISUAL_FIXTURE
 * owner = visual_fixture 전용. production `/` fallback으로 import 금지.
 * KRW 문자열은 이미 포맷됨 — 환율 1360을 코드에 박지 않음.
 * duration = Founder-approved minute fixture 없음 → null(—).
 * day→minute 환산 · 임의 분 발명 금지. production owner = estimatedDurationSec.
 */

import type { SparkDashHomeModel } from "./types";

export const SPARK_DASH_FIXTURE_OWNER = "visual_fixture" as const;

export const SPARK_DASH_DESKTOP_VISUAL_FIXTURE: SparkDashHomeModel = {
  owner: SPARK_DASH_FIXTURE_OWNER,
  displayName: "퍼뜩님",
  levelLabel: "Lv.3",
  sidebarBalance: { usdt: "2,450.00", krw: "≈ ₩3,332,000" },
  walletHeadline: { usdt: "2,450.00", krw: "≈ ₩3,332,000" },
  walletRows: [
    {
      key: "available",
      label: "사용 가능",
      usdt: "2,450.00 USDT",
      krw: "≈ ₩3,332,000",
      tone: "green",
    },
    {
      key: "participating",
      label: "참여 중",
      usdt: "800.00 USDT",
      krw: "≈ ₩1,088,000",
      tone: "blue",
    },
    {
      key: "pending",
      label: "정산 대기",
      usdt: "320.00 USDT",
      krw: "≈ ₩435,200",
      tone: "amber",
    },
    {
      key: "withdrawable",
      label: "출금 가능",
      usdt: "1,250.00 USDT",
      krw: "≈ ₩1,700,000",
      tone: "purple",
    },
  ],
  hero: {
    partner: "eBay",
    partnerKind: "ebay",
    title: "Nike Air Force 1 '07",
    productMediaUrl: "/spark-dash/product-sneaker-hero.png",
    productMediaAlt: "Nike Air Force 1 '07",
    ratePct: "28.4%",
    expectedProfitUsdt: "+284.00 USDT",
    expectedProfitKrw: "≈ ₩386,240",
    durationLabel: null,
    capitalUsdt: "1,000",
    capitalKrw: "≈ ₩1,360,000",
    statusLabel: "참여 가능",
    statusCopy: "조건을 확인한 뒤 참여할 수 있어요.",
    participateHref: "/profits",
    detailHref: "/profits",
  },
  stats: [
    {
      key: "active",
      label: "참여 중 기회",
      value: "3건",
      usdt: "총 1,600 USDT",
      krw: "≈ ₩2,176,000",
      tone: "blue",
    },
    {
      key: "pending",
      label: "정산 대기",
      value: "1건",
      usdt: "320 USDT",
      krw: "≈ ₩435,200",
      tone: "purple",
    },
    {
      key: "month",
      label: "이번 달 수익",
      value: "+180.45 USDT",
      usdt: null,
      krw: "≈ ₩245,412",
      tone: "green",
    },
    {
      key: "lifetime",
      label: "누적 수익",
      value: "+1,250.75 USDT",
      usdt: null,
      krw: "≈ ₩1,701,020",
      tone: "red",
    },
  ],
  popular: [
    {
      id: "fixture-ps5",
      partner: "Amazon",
      partnerKind: "amazon",
      title: "PlayStation 5",
      ratePct: "27.7%",
      expectedProfitUsdt: "+346.25 USDT",
      expectedProfitKrw: "≈ ₩470,900",
      durationLabel: null,
      capitalUsdt: "1,250 USDT",
      capitalKrw: "≈ ₩1,700,000",
      statusLabel: "조건 확인 후 참여 가능",
      href: "/profits",
    },
    {
      id: "fixture-iphone",
      partner: "Yahoo! JAPAN Auction",
      partnerKind: "yahoo",
      title: "iPhone 15 Pro",
      ratePct: "24.3%",
      expectedProfitUsdt: "+267.30 USDT",
      expectedProfitKrw: "≈ ₩363,528",
      durationLabel: null,
      capitalUsdt: "1,100 USDT",
      capitalKrw: "≈ ₩1,496,000",
      statusLabel: "조건 확인 후 참여 가능",
      href: "/profits",
    },
    {
      id: "fixture-airpods",
      partner: "eBay",
      partnerKind: "ebay",
      title: "AirPods Pro 2",
      ratePct: "26.1%",
      expectedProfitUsdt: "+234.90 USDT",
      expectedProfitKrw: "≈ ₩319,464",
      durationLabel: null,
      capitalUsdt: "900 USDT",
      capitalKrw: "≈ ₩1,224,000",
      statusLabel: "조건 확인 후 참여 가능",
      href: "/profits",
    },
    {
      id: "fixture-switch",
      partner: "Amazon Japan",
      partnerKind: "amazon",
      title: "Nintendo Switch",
      ratePct: "23.8%",
      expectedProfitUsdt: "+226.10 USDT",
      expectedProfitKrw: "≈ ₩307,496",
      durationLabel: null,
      capitalUsdt: "950 USDT",
      capitalKrw: "≈ ₩1,292,000",
      statusLabel: "조건 확인 후 참여 가능",
      href: "/profits",
    },
  ],
  nav: [
    { key: "home", label: "홈", href: "/", icon: "home" },
    { key: "explore", label: "기회 탐색", href: "/profits", icon: "explore" },
    { key: "assets", label: "내 자산", href: "/wallet", icon: "wallet" },
    { key: "participations", label: "참여 내역", href: "/trades", icon: "list" },
    { key: "settlements", label: "정산 내역", href: "/wallet/history", icon: "receipt" },
    { key: "partners", label: "파트너", href: "/me/guide/partners", icon: "partner" },
    { key: "alerts", label: "알림", href: "/me/inbox", icon: "bell" },
    { key: "settings", label: "설정", href: "/me/settings", icon: "settings" },
  ],
};
