/**
 * T.admin.* — Admin plain language §27.5 · cute tone 0
 * Canon wire copyKeys · UI app implementation 0 for Admin Owns surfaces
 */
export const admin = {
  productName: "퍼뜩 운영센터",
  productDescription: "퍼뜩 서비스를 안전하게 관리하는 곳",
  adminOnly: "관리자 전용",
  skipToContent: "본문으로 바로가기",
  openMenu: "전체 메뉴 열기",
  closeMenu: "전체 메뉴 닫기",
  navigationLabel: "운영 메뉴",
  navigation: {
    dashboard: "오늘 할 일",
    opportunities: "수익 기회 관리",
    executionPolicy: "수익 진행 기준",
    adapters: "해외 가격 확인",
    wallet: "입출금 관리",
    ledger: "돈의 이동 기록",
    users: "회원 관리",
    risk: "의심 거래 확인",
    compliance: "본인 확인·이용 제한",
    systemControl: "서비스 긴급 멈춤",
    aiLogs: "퍼뜩 판단 기록",
    growth: "혜택·행사 관리",
    audit: "관리자 작업 기록",
  },
  navigationGroups: {
    today: "오늘 먼저 확인",
    profit: "수익 운영",
    moneyAndPeople: "돈과 회원",
    safety: "안전과 지원",
    records: "분석과 기록",
  },
  session: {
    connected: "관리자 연결이 완료됐어요",
    disconnected: "관리자 연결이 필요해요",
    connectedHint: "허용된 관리 기능을 사용할 수 있습니다.",
    disconnectedHint: "정보를 확인하거나 바꾸려면 먼저 연결해 주세요.",
    open: "관리자 연결하기",
    change: "연결 정보 바꾸기",
    codeLabel: "관리자 연결 코드",
    codeHint: "관리자 로그인에서 받은 코드를 붙여 넣어 주세요. 이 기기에만 보관됩니다.",
    codePlaceholder: "관리자 연결 코드를 입력하세요",
    connect: "연결 완료",
    disconnect: "연결 끊기",
  },
  dashboard: {
    eyebrow: "운영 홈",
    title: "오늘 필요한 일부터 확인하세요",
    description:
      "실제로 확인된 정보만 보여 드립니다. 준비되지 않은 숫자는 0으로 꾸미지 않습니다.",
    attentionTitle: "바로 확인할 곳",
    attentionDescription: "문제가 생기면 아래 순서대로 살펴보세요.",
    quickActions: {
      suspicious: "확인이 필요한 거래",
      identity: "본인 확인 요청",
      money: "입출금 확인",
      support: "고객 문의",
    },
    statusTitle: "서비스 상태",
    userCount: "전체 회원",
    userCountUnavailable:
      "회원 목록 연결이 준비되지 않아 숫자를 표시하지 않습니다.",
    push: "알림 보내기",
    moneyFlow: "수익 진행",
    queue: "확인이 필요한 거래",
    viewDetails: "자세히 보기",
    normal: "정상",
    paused: "멈춤",
    on: "사용 중",
    off: "멈춤",
  },
  state: {
    loading: "정보를 불러오고 있어요",
    empty: "지금 확인할 내용이 없습니다.",
    unavailable: "현재 정보를 확인할 수 없습니다.",
    unavailableHint: "잠시 후 다시 확인해 주세요. 없는 숫자를 임의로 표시하지 않습니다.",
    unauthorized: "먼저 관리자 연결을 완료해 주세요.",
    forbidden: "현재 관리자에게 허용되지 않은 작업입니다.",
    notFound: "요청한 내용을 찾지 못했습니다.",
    error: "요청을 마치지 못했습니다. 잠시 후 다시 시도해 주세요.",
  },
  usersList: {
    totalCountLabel: "전체 회원",
    countUnit: "명",
    searchLabel: "회원 찾기",
    searchPlaceholder: "아이디, 이메일, 이름으로 찾기",
    statusLabel: "이용 상태",
    statusAll: "전체",
    statusActive: "이용 중",
    statusBanned: "이용 정지",
    statusDeleted: "삭제됨",
    signupMethodLabel: "가입 방식",
    signupAll: "전체",
    signupClassic: "일반 가입",
    signupKakao: "카카오 로그인",
    signupGoogle: "구글 로그인",
    signupPasskey: "패스키",
    signupEmailMagic: "이메일 링크 로그인",
    orderLabel: "정렬",
    orderDesc: "최근 가입순",
    orderAsc: "오래된 가입순",
    emailVerifiedYes: "이메일 인증 완료",
    emailVerifiedNo: "이메일 인증 전",
    pageLabel: "페이지",
    prevPage: "이전 페이지",
    nextPage: "다음 페이지",
    retry: "다시 확인",
  },
  twelveModules: "운영 메뉴 12",
  savePolicy: "변경 내용 저장",
  matchSuccessControl: "수익 기회 선택 기준",
  executionRealGuards: "실제 진행 기준",
  executionPresentation: "화면 표시 방식",
  observedSuccessRate: "오늘 실제 완료 비율(보기만 가능)",
  nearMissCapUsdt: "아쉽게 놓친 기회로 분류할 금액 한도(테더)",
  growthTabs: "혜택과 행사",
  contentTab: "안내 문구",
  taxDisclaimerLocked: "세금 안내 문구(이 화면에서 변경할 수 없음)",
  taxDisclaimerLockedHint:
    "회원에게 보여 주는 세금 안내는 검토된 공통 문구라서 여기서는 바꿀 수 없습니다.",
  simulationGates: "행사 시작 전 안전 점검",
  simulationKpiInputs: "점검에 쓰는 실제 정보",
  growthEnabled: "혜택·행사 시작",
  simulationLatest: "최근 안전 점검",
  systemControlTabs: "서비스 멈춤 관리",
  platformReserveTarget: "운영 준비금 목표",
  platformReserveS2: "준비금 안전 점검",
  platformReserveAudit: "준비금 변경 기록",
  adaptersCollectors: "가격을 가져오는 곳",
  adaptersListingLegs: "당일 가격 비교 범위",
  adaptersMatchingKpi: "상품 연결 정확도",
  adaptersAlerts: "가격 확인 알림",
  adaptersYahoo0: "야후 일본 경매는 당일 자동 공개에서 제외",
  aiLogsTabs: "퍼뜩 판단 기록",
  aiLogsTraces: "답변이 만들어진 과정",
  aiPickScores: "퍼뜩 추천 근거",
  aiEvalGate: "서비스에 쓰기 전 확인",
  aiCoach: "퍼뜩 답변 기준",
  toast: {
    depositReview: "입금 검수 대기",
    policySaved: "변경 내용을 저장했습니다",
  },
} as const;

export type AdminCopy = typeof admin;
