/** UI §5.9.5 · Money §51.8a — Benefit Hub copy SSOT */
export const benefits = {
  title: "혜택 · 미션",
  heroMonthly: "이번 달 받은 보너스",
  heroClaimable: "받을 혜택",
  heroPending: "확인 중",
  heroEducation: "배울 미션",
  heroEducationHint: "보너스는 나중에 열려요. 지금은 미션을 익혀 보세요.",
  dailyReset: "오늘 미션 · {time} 후 리셋",
  sectionDaily: "오늘",
  sectionOneTime: "처음 한 번",
  sectionWeekly: "이번 주",
  sectionStreak: "연속",
  sectionEmpty: "아직 받을 미션이 없어요",
  carouselTitle: "진행 중 이벤트",
  carouselEmpty: "진행 중 이벤트가 없어요",
  statusReleased: "받았어요",
  statusStart: "시작하기",
  statusContinue: "이어하기",
  statusInProgress: "진행 중",
  statusPending: "확인 중…",
  statusPoolWait: "보너스 준비 중",
  statusExpired: "종료됐어요",
  statusLocked: "준비 중",
  practiceBadge: "연습",
  profitBadge: "수익",
  couponBadge: "수수료 할인",
  rewardPractice: "연습 +{amount}",
  rewardProfit: "수익 +{amount}",
  rewardCoupon: "출금 수수료 -{amount}",
  rewardUsdtSuffix: "USDT",
  rewardKrwApprox: "≈₩{amount}",
  footerInvite: "친구 초대는 여기",
  footerEvents: "이벤트 더보기",
  poolWaitNote: "보너스 준비 중이에요. 미션이 취소된 건 아니에요.",
  noVirtualCurrencyNote: "보너스는 지갑 수익·연습·수수료 할인으로 들어와요.",
  poolFaqCta: "자세히 알아보기",
  moneyPointer: "Money §51.8a",
  enginePointer: "Engine §48.13.4",
  adminPointer: "Admin growth?tab=missions",
} as const;

/** 하위 호환 — 일부 verify/문서가 `T.benefits` nested export를 기대 */
export const T = { benefits } as const;
