/**
 * T.onboarding.* — PUTDUK Automation Story (Figma 237:1813 / 237:2155)
 * 유저 대면 7단: 탐색 → 매칭 → 계산 → 검증 → 준비 → 결정 → 실행
 * 내부 스텝 키(tone/identity/…)는 UI에 노출하지 않는다.
 * 온보딩 교육 숫자는 개념 라벨만. 가짜 금액 0.
 */
export const onboarding = {
  brand: "퍼뜩",
  back: "이전",
  skip: "나중에 알아볼게요",
  resolving: "잠시만요",
  resolvingHint: "이어서 안내를 준비하고 있어요.",
  retry: "다시 시도",
  stepRailLabel: "안내 단계",
  stepOf: (current: number, total: number) => `${current} / ${total}`,

  story: {
    tone: {
      key: "tone",
      n: 1,
      label: "탐색",
      title: "전 세계 시세차익 기회, 퍼뜩 AI가 먼저 찾아요",
      titleMobile: "전 세계 기회, 퍼뜩 AI가 먼저 찾아요",
      body: "여러 글로벌 시장을 자동으로 살펴보고, 가격 차이가 생긴 상품 후보를 먼저 좁혀요.",
      bodyMobile: "여러 시장을 자동으로 살펴 시세차익 후보를 좁혀요.",
      caption: "나는 찾지 않아도 돼요. 퍼뜩이 먼저 후보를 만들어요.",
      captionMobile: "퍼뜩이 먼저 찾고 나는 결과를 봐요.",
      next: "자동 매칭 보기",
    },
    identity: {
      key: "identity",
      n: 2,
      label: "매칭",
      title: "같은 상품을 퍼뜩 AI가 자동으로 연결해요",
      body: "상품명이 달라도 브랜드·모델·규격·특징을 함께 보고 같은 상품인지 확인해요.",
      caption: "같은 상품을 사람이 일일이 찾지 않아도 돼요.",
      next: "수익 계산 보기",
    },
    partner: {
      key: "partner",
      n: 3,
      label: "계산",
      title: "가격 차이가 실제 수익인지 자동으로 계산해요",
      body: "매입 조건·수수료·환율·비용까지 반영해 필요한 원금과 예상 수익을 계산해요.",
      caption: "실제 기회에서는 계산된 원금·예상 수익·예상 시간을 보여드려요.",
      next: "검증 과정 보기",
    },
    demo: {
      key: "demo",
      n: 4,
      label: "검증",
      title: "실제로 진행 가능한 기회인지 한 번 더 검증해요",
      body: "상품 일치·출처·가격 상태·비용·참여 가능 여부를 다시 확인해요.",
      caption: "검증 기준을 통과한 기회만 사용자에게 보여줘요.",
      next: "참여 준비 보기",
    },
    usdt: {
      key: "usdt",
      n: 5,
      label: "준비",
      title: "참여할 때, 편한 방법으로 준비할 수 있어요",
      titleMobile: "참여할 때 편한 방법으로 준비해요",
      body: "원화 또는 테더(USDT) 중 편한 방법을 선택할 수 있어요. 지금은 입금하지 않아도 돼요.",
      bodyMobile: "원화·USDT 중 선택할 수 있어요. 지금은 입금하지 않아도 돼요.",
      caption: "돈을 넣지 않아도 기회를 먼저 둘러볼 수 있어요.",
      captionMobile: "기회를 먼저 둘러본 뒤 결정해도 돼요.",
      next: "방법 확인했어요",
    },
    action: {
      key: "action",
      n: 6,
      label: "결정",
      title: "원금·예상 수익·예상 시간을 보고 내가 결정해요",
      body: "퍼뜩이 기회를 찾아도 자동으로 내 돈을 사용하지 않아요. 내가 확인하고 참여해야 시작돼요.",
      caption: "내가 누르기 전에는 참여가 시작되지 않아요.",
      next: "자동 실행 과정 보기",
    },
    payout: {
      key: "payout",
      n: 7,
      label: "실행",
      title: "참여하면, 실행 과정은 퍼뜩이 이어서 처리해요",
      titleMobile: "참여 후 실행은 퍼뜩이 이어서 처리해요",
      body: "조건을 다시 확인하고 실행·진행 상태·정산 결과까지 보여드려요. 예상 시간은 기회마다 분·시간 단위로 확인해요.",
      bodyMobile: "재확인·실행·진행 상태·정산 결과를 보여드려요.",
      caption: "찾는 것부터 실행까지, 복잡한 과정은 퍼뜩이 줄여드려요.",
      captionMobile: "예상 시간은 기회마다 분·시간 단위로 확인해요.",
      next: "첫 기회 둘러보기",
    },
  },

  visual: {
    explore: {
      sourceKicker: "세계 시장 신호",
      sourceTitle: "퍼뜩이 여러 시장을 대신 살펴봐요",
      sourceBody: "상품·가격·판매 상태 신호를 자동으로 모아 비교 준비를 해요.",
      markets: [
        { name: "eBay", signal: "상품·가격 신호" },
        { name: "Amazon", signal: "상품·가격 신호" },
        { name: "야후 재팬 옥션", signal: "상품·판매 신호" },
      ],
      aiKicker: "PUTDUK AI",
      aiTitle: "자동 탐색",
      aiBody: "사람이 일일이 찾기 전에 퍼뜩이 먼저 후보를 좁혀요.",
      scans: [
        { left: "상품 신호", right: "같은 상품 후보 찾기" },
        { left: "시장 가격", right: "가격 차이 후보 찾기" },
        { left: "판매 상태", right: "실행 가능성 확인" },
      ],
      resultKicker: "자동 탐색 결과",
      resultTitle: "시세차익 후보를 정리해요",
      resultBody: "아직 참여가 아니라 다음 자동 검토로 넘겨요.",
      results: [
        { left: "같은 상품 후보", right: "찾음" },
        { left: "시장 간 가격차", right: "검토" },
        { left: "실행 가능성", right: "다음 단계" },
      ],
      resultFoot: "퍼뜩이 먼저 찾고, 사용자는 결과를 봐요.",
      mobileAiTitle: "세계 시장을 자동으로 탐색해요",
      mobileAiBody: "상품·가격·판매 신호를 먼저 모아 차익 후보를 좁혀요.",
      mobileSources: ["eBay", "Amazon", "야후 재팬"],
      mobileResultLeft: "자동 탐색 결과",
      mobileResultRight: "시세차익 후보 → 자동 매칭으로",
    },
    match: {
      marketAKicker: "시장 A · eBay",
      marketATitle: "상품 정보 A",
      marketABody: "표현이 달라도 핵심 특징을 읽어요.",
      marketBKicker: "시장 B · 글로벌 시장",
      marketBTitle: "상품 정보 B",
      marketBBody: "다른 이름·표현도 특징으로 비교해요.",
      attrs: ["브랜드", "모델·규격", "상품 특징", "카테고리"],
      attrState: "확인",
      aiKicker: "PUTDUK AI MATCH",
      aiTitle: "같은 상품인지 자동으로 맞춰요",
      aiBody: "상품명 하나만 보는 게 아니라 여러 특징을 함께 확인해요.",
      matchResult: "같은 상품으로 연결",
      marketBFoot: "사람이 일일이 같은 상품을 찾지 않아도 돼요.",
      tabletAiTitle: "AI MATCH",
      tabletAiState: "자동 확인",
      tabletCriteria: "같은 상품인지 여러 특징을 함께 확인해요",
      tabletResult: "같은 상품으로 자동 연결",
      tabletAttrs: "브랜드 · 모델 · 규격 · 특징",
    },
    calc: {
      principleKicker: "가격 차이만 보면 안 돼요",
      principleTitle: "실제로 남는 금액을 계산해요",
      principleBody: "매입 조건부터 비용·환율까지 함께 반영해 예상 수익을 봐요.",
      inputs: ["매입 조건", "시장 가격차", "수수료·비용", "환율"],
      principleFoot: "숫자는 실제 기회에서 계산돼요.",
      engineKicker: "PUTDUK AI 계산",
      engineTitle: "차익 후보 → 실제 예상 수익",
      engineBody: "단순 가격 비교가 아니라 실행 전 계산이에요.",
      stages: [
        { n: "1", title: "매입 조건", state: "반영" },
        { n: "2", title: "가격 차이", state: "반영" },
        { n: "3", title: "비용·환율", state: "반영" },
        { n: "4", title: "예상 수익", state: "자동 계산" },
      ],
      engineNote: "실제 기회에서는 필요 원금·예상 수익·예상 시간까지 함께 표시해요.",
      outKicker: "자동 계산 결과",
      outTitle: "참여 전에 핵심 숫자를 보여줘요",
      outputs: [
        { left: "필요 원금", right: "실제 값 표시" },
        { left: "예상 수익", right: "비용 반영" },
        { left: "예상 시간", right: "분·시간 단위" },
      ],
      outFoot: "예상값은 기회 조건에 따라 달라져요.",
    },
    validate: {
      listKicker: "자동 검증",
      listTitle: "계산됐다고 바로 보여주지 않아요",
      listBody: "실제로 진행할 수 있는 기회인지 한 번 더 확인해요.",
      items: [
        { n: "01", title: "상품 일치", detail: "같은 상품인지" },
        { n: "02", title: "출처", detail: "정보 근거가 있는지" },
        { n: "03", title: "가격·판매 상태", detail: "현재 조건이 유효한지" },
        { n: "04", title: "수수료·환율", detail: "계산 조건이 맞는지" },
        { n: "05", title: "참여 가능 여부", detail: "실행 가능한지" },
      ],
      listFoot: "조건이 바뀌면 다시 확인하거나 기회를 숨겨요.",
      resultKicker: "검증 결과",
      resultTitle: "검증된 기회만 사용자에게 보여줘요",
      resultBody: "찾았다는 이유만으로 참여 화면에 올리지 않아요.",
      flow: ["후보 발견", "수익 계산", "조건 검증", "기회 노출"],
      resultFoot: "사용자는 검증된 조건을 보고 결정해요.",
    },
    prepare: {
      lead: "기회를 먼저 보고, 참여할 때 필요한 방법만 준비해요.",
      krwTitle: "KRW (원화)",
      krwBody: "익숙한 원화 방식으로 준비",
      usdtTitle: "USDT (테더)",
      usdtBody: "이미 보유 중이라면 사용 가능",
      krwRows: [
        { left: "국내 계좌 기반", right: "방법 확인" },
        { left: "필요 금액", right: "기회에서 확인" },
        { left: "실제 준비", right: "참여할 때" },
      ],
      usdtRows: [
        { left: "지갑·거래소", right: "방법 확인" },
        { left: "필요 금액", right: "기회에서 확인" },
        { left: "실제 준비", right: "참여할 때" },
      ],
      timing: ["기회 먼저 확인", "조건 확인", "참여할 때 준비"],
    },
    decide: {
      truthKicker: "참여 전 마지막 확인",
      truthTitle: "핵심 조건을 보고 내가 결정해요",
      truthBody: "퍼뜩이 찾고 계산해도 내 선택 없이 시작하지 않아요.",
      metrics: [
        { left: "필요 원금", right: "실제 금액 표시", emphasize: false },
        { left: "예상 수익", right: "비용 반영 예상", emphasize: false },
        { left: "예상 시간", right: "분·시간 단위", emphasize: true },
        { left: "참여 가능 여부", right: "현재 조건 확인", emphasize: false },
      ],
      truthFoot: "예상값과 조건을 충분히 확인한 뒤 결정해요.",
      controlKicker: "결정권은 사용자에게",
      controlTitle: "내가 누르기 전에는 참여가 시작되지 않아요",
      controlSteps: ["퍼뜩이 기회 제안", "내가 조건 확인", "내가 참여 결정"],
      controlReady: "확인 후 내가 시작",
    },
    run: {
      introKicker: "참여 후",
      introTitle: "복잡한 실행 과정은 퍼뜩이 이어서 처리해요",
      introBody: "사용자는 진행 상태와 결과를 계속 확인할 수 있어요.",
      timeLabel: "예상 시간",
      timeValue: "기회마다 분·시간 단위",
      uncertainty: "실제 결과는 기회 조건에 따라 달라질 수 있어요",
      flowKicker: "PUTDUK EXECUTION",
      flowTitle: "참여 후 실행 상태를 단계별로 보여줘요",
      flowBody: "기회 조건에 따라 실제 상태와 예상 시간이 달라질 수 있어요.",
      stages: [
        { n: "1", title: "참여 요청", state: "사용자 확인" },
        { n: "2", title: "조건 재확인", state: "최신 조건" },
        { n: "3", title: "실행", state: "자동 처리" },
        { n: "4", title: "진행 추적", state: "상태 확인" },
        { n: "5", title: "정산·Wallet", state: "결과 반영" },
      ],
      flowNote: "찾는 것부터 실행까지, 퍼뜩이 자동화하고 사용자는 상태를 확인해요.",
    },
  },
  /** 설정 설명 길이. 온보딩 첫 화면이 아님. */
  young: { pace: "짧게" },
  mid: { pace: "비교로" },
  senior: { pace: "한 줄씩" },
} as const;

export type OnboardingCopy = typeof onboarding;
export type OnboardingStoryKey = keyof typeof onboarding.story;
