/**
 * T.walletBuckets / T.withdrawMode / T.successBucketCta — Money §49.8
 * JSX 하드코딩 금지 · 원금 출금 숨김·위협성 금지어 0 (§49.5)
 * Presentation = Wallet V2 Figma. "고급"/developer label 0.
 */
export const walletBuckets = {
  pageTitle: "지갑",
  eyebrow: "내 자산",
  subtitle: "입금·출금·수익 내역을 한곳에서 확인해요",
  truthBadge: "내 자산",
  totalLabel: "총 잔액",
  krwUnavailable: "원화 환산액은 확인할 수 있을 때 함께 보여드려요",
  krwPlaceholder: "≈ — KRW",
  assurance: "정확하게 확인된 금액만 보여드려요",
  compositionHeading: "자산 구성",
  compositionNote: "한눈에 보기",
  workingPrincipal: "근무 중 원금",
  workingPrincipalSupport: "다음 기회에 쓰는 원금",
  workingPrincipalSupportShort: "다음 기회용",
  withdrawableProfit: "출금 가능 수익",
  withdrawableProfitSupport: "바로 출금할 수 있는 수익",
  withdrawableProfitSupportShort: "바로 출금 가능",
  locked: "진행 중 잠금",
  lockedSupport: "참여 중 쓰는 금액",
  lockedSupportShort: "참여 중 사용",
  practice: "연습 잔액",
  practiceSupport: "연습에만 사용할 수 있어요",
  defaultProfitHint: "원금은 다음 수익에 쓰이고, 수익만 가져갈 수 있어요",
  principalAlways: "원금은 언제든 출금할 수 있어요",
  guideLink: "원금이 왜 필요해요?",
  usdtSuffix: "USDT",
  missingAmount: "—",
  actionHeading: "필요한 작업",
  actionNote: "빠른 이동",
  ctaDeposit: "입금하기",
  ctaWithdraw: "출금하기",
  historyLink: "입출금·수익 내역",
  depositBody: "테더(USDT) · 원화",
  withdrawBody: "수익만 기본 · 원금 포함 선택",
  historyBody: "기록을 시간순으로 확인",
  startLink: "시작하기",
  historyViewLink: "내역 보기",
  recentHeading: "최근 내역",
  recentEmpty: "아직 표시할 내역이 없어요. 내역이 생기면 여기에 보여요.",
  recentLink: "전체 내역 보기",
  sidebarSummary: "내 자산 요약",
  sidebarAvailable: "사용 가능 자산",
  sidebarAiTitle: "퍼뜩 AI",
  sidebarAiBody: "지금 확인할 수 있는 기회를 정리하고 있어요.",
  headerSafe: "입금·출금·수익을 한곳에서 확인해요",
  headerOpps: "기회 보기",
  accountLink: "내 계정",
  unauthorizedLead: "로그인하면 지갑을 볼 수 있어요.",
  unavailableLead: "지갑 잔액을 확인할 수 없어요. 잠시 후 다시 시도해 주세요.",
  loginCta: "로그인",
  loadingLead: "불러오는 중…",
} as const;

export const withdrawMode = {
  pageTitle: "출금",
  pageTitleUsdt: "테더(USDT) 출금",
  pageTitleKrw: "원화 출금",
  pageLeadUsdt: "출금할 금액과 받을 주소를 확인한 뒤 본인 확인을 거쳐 신청해요.",
  pageLeadKrw: "출금할 자산을 정하고 본인 확인을 거쳐 원화 출금을 신청해요.",
  pageLeadPrincipal: "원금도 함께 출금할 수 있어요.",
  reviewLead: "내용을 확인해 주세요.",
  tabUsdt: "테더(USDT)",
  tabKrw: "원화",
  whatToWithdraw: "무엇을 출금할까요?",
  modeProfit: "수익만",
  modeProfitHint: "출금 가능한 수익을 받아요",
  modePrincipal: "원금 포함",
  modePrincipalHint: "원금까지 함께 출금해요",
  modeCombined: "수익+원금",
  ctaProfitWithdraw: "수익 출금하기",
  ctaOpenPrincipal: "원금 출금하기",
  confirmTitle: "원금도 함께 출금할까요?",
  confirmBody:
    "원금은 다음 기회에 참여할 때 쓰는 금액이에요. 원금을 출금하면 참여할 수 있는 기회가 줄어들 수 있어요.",
  confirmSelfOnly:
    "본인만 진행해 주세요. 다른 분 폰·계정에서는 출금하지 마세요.",
  ctaProfitOnly: "수익만 출금할게요",
  ctaStillPrincipal: "그래도 원금도 출금할게요",
  amountLabel: "출금할 금액",
  amountPlaceholder: "금액 입력",
  availableProfit: "출금 가능한 수익",
  allAmount: "전액",
  feeHint: "이체 수수료는 확인할 수 있을 때만 보여 드려요",
  feeLine: "이체 수수료 {fee} USDT",
  feeLabel: "이체 수수료",
  feeUnavailable: "—",
  destinationLabel: "받는 주소",
  destinationPlaceholder: "테더(USDT) 주소 입력",
  receivePlace: "받는 곳",
  receiveCurrency: "받는 통화",
  receiveKrw: "원화",
  networkField: "받는 네트워크",
  reviewTitle: "출금 내용",
  reviewPreviewTitle: "출금 전에 확인해요",
  reviewMode: "출금 방식",
  reviewAmount: "출금 금액",
  amountPending: "입력 후 표시",
  destPending: "주소 입력 후 표시",
  feePending: "확인 단계에서 표시",
  ctaReview: "출금 내용 확인",
  stepUpTitle: "마지막으로 본인 확인이 필요해요",
  stepUpHint: "확인이 끝나면 출금 신청을 보낼게요.",
  stepUpPinLabel: "출금 비밀번호",
  stepUpPinPlaceholder: "비밀번호 입력",
  stepUpCodeLabel: "확인 코드",
  stepUpChallenge: "확인 요청",
  stepUpVerify: "확인하기",
  ctaStepUpSubmit: "본인 확인하고 출금 신청",
  stepUpLast: "본인 확인은 마지막에",
  stepUpLastBody: "금액과 받는 곳을 먼저 확인한 뒤 필요한 본인 확인을 이어가요.",
  krwNoticeTitle: "원화로 출금을 신청해요",
  krwNoticeBody: "본인 확인을 마친 뒤 원화 출금 요청을 접수해요.",
  krwTruthTitle: "확인되지 않은 금액은 만들지 않아요",
  krwTruthBody: "원화 수령액은 실제로 확인 가능한 값이 있을 때만 보여줘요.",
  ctaSubmit: "출금 신청",
  submitOk: "출금 신청을 접수했어요",
  submitFail: "출금을 진행하지 못했어요. 잠시 후 다시 해 주세요",
  unauthorized: "로그인하면 출금을 신청할 수 있어요.",
  denied: "지금은 출금할 수 없어요.",
} as const;

export const successBucketCta = {
  ctaProfitOnly: "수익만 출금",
  ctaMerge: "원금에 합치기",
  ctaLater: "나중에",
  emphasisDefault: "profit_withdraw",
} as const;

export const principalGuide = {
  pageTitle: "원금과 수익",
  whyKeep:
    "원금은 다음 기회에 바로 쓸 수 있는 근무 중 자본이에요. 수익만 출금해도 괜찮아요.",
  alwaysWithdraw: "원금도 언제든 출금할 수 있어요. 숨기거나 막지 않아요.",
  mergeHint: "수익을 원금에 합치면 더 큰 기회에 참여할 수 있어요.",
} as const;

/** Nested under T for wallet/withdraw surfaces */
export const principalProfit = {
  walletBuckets,
  withdrawMode,
  successBucketCta,
  principalGuide,
} as const;

export type PrincipalProfitCopy = typeof principalProfit;
