export const productOnboarding = {
  progressLabel: "{current}/{total} 단계",
  virtualBadge: "가상 예시 · 실제 거래 아님",
  largeType: "큰 글씨",
  easyExplain: "더 쉽게 설명",
  next: "다음",
  back: "이전",
  later: "나중에 둘러보기",
  practiceCta: "연습으로 참여해 보기",
  confirmPractice: "이 예시로 다음 설명을 볼까요?",
  confirmYes: "계속 보기",
  startApp: "시작하기",
  unavailable: "확인할 수 없음",
  usdtUnit: "USDT",
  krwApprox: "≈ ₩{amount} · 환율 참고",
  expectedNotSettled: "확정 수익 아님",
  expectedLabel: "예상 수익",
  settledLabel: "정산 완료 수익",
  requiredLabel: "필요 원금",
  availableLabel: "사용 가능",
  shortfallLabel: "부족 금액",
  noDepositNow: "지금은 입금하지 않아도 돼요. 금액만 확인하면 됩니다.",
  objection: "회사는 마진으로 · 나는 내 자본으로",
  closing: "퍼뜩 AI가 탐색·매칭·계산·검증하고, 사용자가 금액을 확인해 결정해요.",
  search: {
    title: "퍼뜩 AI가 전 세계 가격을 모아요",
    body: "한 곳만 보는 게 아니라, 같은 상품의 가격을 여러 시장에서 비교해요.",
    easyBody: "여러 나라 가격을 한곳으로 모아 보여 드려요.",
  },
  match: {
    title: "정말 같은 상품인지 먼저 확인해요",
    body: "모델명·상품상태·식별자·판매조건을 비교해 같은 상품인지 확인해요.",
    easyBody: "이름과 상태가 같은 상품인지 먼저 맞춰 봐요.",
    model: "모델명",
    condition: "상품 상태",
    identifier: "식별자",
    saleTerms: "판매 조건",
    hold: "검증 보류",
    matched: "같은 상품",
  },
  calc: {
    title: "보이는 차익에서 모든 비용을 빼요",
    body: "판매 예상가에서 사는 가격·수수료·배송비·환율 비용을 뺀 값이 예상 수익이에요.",
    easyBody: "받을 돈에서 들어간 돈을 모두 빼고 남을 돈을 보여 드려요.",
    sell: "판매 예상가",
    buy: "사는 가격",
    fee: "수수료",
    shipping: "배송비",
    fx: "환율·기타 비용",
    expected: "예상 수익",
  },
  verify: {
    title: "계산이 맞는지 다시 검사해요",
    body: "가격 최신성·동일 상품·비용 완전성·정책을 순서대로 확인해요.",
    easyBody: "숫자가 맞는지 한 번 더 살펴요.",
    freshness: "가격 최신성",
    identity: "동일 상품",
    costComplete: "비용 완전성",
    policy: "정책 통과",
    holdReason: "아직 부족한 항목이 있어 수익을 지급하지 않아요.",
    passed: "확인됨",
  },
  capital: {
    title: "참여에 필요한 원금을 확인해요",
    body: "필요 원금이 주 금액이에요. 아래 원화는 참고값입니다.",
    easyBody: "이 기회에 필요한 금액만 먼저 확인해요.",
  },
  decision: {
    title: "마지막 선택은 사용자가 해요",
    body: "원금·예상 수익·소요 시간·검증 시각을 보고 연습 참여 여부를 직접 정해요.",
    easyBody: "금액을 보고 사용자가 직접 결정해요. AI가 대신 넣거나 빼지 않아요.",
    duration: "예상 소요",
    durationValue: "약 60분",
    checkedAt: "검증 시각",
  },
  settle: {
    title: "성공과 안전중단은 이렇게 달라요",
    body: "성공하면 원금과 실제 정산 수익이 들어와요. 안전중단되면 원금만 한 번 돌아와요.",
    easyBody: "잘되면 원금과 정산 수익, 멈추면 원금만 돌아와요.",
    successTitle: "성공",
    stopTitle: "안전중단",
    lock: "원금 잠금",
    successConfirm: "권위 있는 성공 확인",
    successCredit: "원금 + 실제 정산 수익 반영",
    stopConfirm: "안전중단",
    stopCredit: "원금만 1회 반환, 수익 0",
  },
} as const;

export type ProductOnboardingCopy = typeof productOnboarding;
