/**
 * URL path compatibility only.
 * route existence ≠ UX authority.
 * No tab order, icon, label, or active-nav metadata.
 */
export const USER_ROUTE_PATHS = [
  "/",
  "/profits",
  "/trades",
  "/wallet",
  "/me",
  "/wallet/deposit",
  "/wallet/withdraw",
  "/wallet/withdraw/usdt",
  "/wallet/withdraw/krw",
  "/wallet/history",
  "/me/settings",
  "/me/legal",
  "/me/legal/terms",
  "/me/legal/privacy",
  "/me/legal/oss",
  "/me/legal/license",
  "/me/kyc",
  "/me/peotteok",
  "/me/membership",
  "/me/inbox",
  "/me/invite",
  "/me/events",
  "/me/strategies",
  "/me/support",
  "/me/benefits",
  "/me/guide/usdt",
  "/me/guide/get-usdt",
  "/me/guide/revenue",
  "/me/guide/faq",
  "/me/guide/principal",
  "/me/guide/partners",
  "/me/guide/market-weekly",
  "/trades/[id]/execute",
  "/profits/[id]",
  "/onboarding",
  "/auth/login",
  "/auth/signup",
  "/auth/complete-profile",
  "/l/[variant]",
  "/ads",
  "/ads/[variant]",
] as const;

export const WEB_FORBIDDEN_PREFIXES = ["/admin"] as const;
