/** @aipo/sdk — Phase0 skeleton (install/push/haptics/marketing land in domain todos) */
export {
  detectDeviceTier,
  tierBatchMs,
  type DeviceTier,
  type StreamPolicyBands,
} from "./device-tier";

export {
  DEFAULT_EXECUTION_TRANSPORT,
  PHASE1_EXECUTION_SSE_PATH,
  TERMINAL_EXECUTION_STATUSES,
  TradeExecutionRequestError,
  createExecutionTransport,
  createPollingTransport,
  createSseTransport,
  isTerminalExecutionStatus,
  isTradeExecutionRequestError,
  useTradeExecution,
  type ExecutionSubscribeOptions,
  type ExecutionTransportKind,
  type TradeExecutionRequestCode,
  type TradeExecutionResultCode,
  type TradeExecutionState,
  type TradeExecutionStatus,
  type TradeExecutionStepIndex,
  type TradeExecutionTransport,
  type UseTradeExecutionOptions,
  type UseTradeExecutionResult,
} from "./execution-stream";

export {
  fetchPeotteokChips,
  streamPeotteokChat,
  usePeotteokChat,
  type PeotteokChatDone,
  type PeotteokChatMeta,
  type PeotteokChip,
  type PeotteokChipsResponse,
  type PeotteokLane,
  type PeotteokMessage,
  type PeotteokToneBand,
  type UsePeotteokChatOptions,
  type UsePeotteokChatResult,
} from "./peotteok";

export {
  ParticipateError,
  issuePreflight,
  isParticipateError,
  newParticipateIdempotencyKey,
  postParticipate,
  readParticipateErrorCode,
  type ParticipateRequestBody,
  type ParticipateRequestOpts,
  type ParticipateResult,
  type PreflightResponse,
} from "./participate";

export {
  OpportunityFeedError,
  fetchDayPulse,
  fetchOpportunityDetail,
  fetchOpportunityFeed,
  isOpportunityFeedError,
  mapNearMissExtraCount,
  readOpportunityFeedItem,
  readOpportunityFeedItems,
  type DayPulseResponse,
  type OpportunityAssetImageSource,
  type OpportunityDetailResponse,
  type OpportunityFeedItem,
  type OpportunityFeedResponse,
  type UserFeedRequestOpts,
} from "./user-feed";

export {
  fetchTradeList,
  type TradeListRequestOpts,
  type TradeListResponse,
} from "./trades";

export {
  CONSUMER_PROFIT_MERGE_CTA_EXPOSED,
  createDepositDispute,
  createKrwDepositRequest,
  createWithdraw,
  createWithdrawStepUpChallenge,
  fetchKycStatus,
  fetchMyDepositAddress,
  fetchWalletBuckets,
  getKrwDepositRequest,
  listKrwDepositRequests,
  listWalletJournals,
  newDepositDisputeIdempotencyKey,
  newWithdrawIdempotencyKey,
  normalizeDepositAddress,
  normalizeDepositDispute,
  normalizeKrwDepositRequest,
  normalizeKycStatus,
  normalizeWalletBuckets,
  normalizeWalletJournals,
  submitKyc,
  verifyWithdrawStepUp,
  type CreateDepositDisputeInput,
  type CreateKrwDepositInput,
  type CreateWithdrawInput,
  type DepositDispute,
  type DepositDisputeKind,
  type DepositDisputeStatus,
  type KycStatus,
  type KycStatusResponse,
  type KrwDepositFinal,
  type KrwDepositQuote,
  type KrwDepositRequest,
  type PayableSuffixRole,
  type SubmitKycInput,
  type UserDepositAddress,
  type WalletBucketsResponse,
  type WalletJournalItem,
  type WalletJournalLine,
  type WalletJournalsResponse,
  type WalletRequestOpts,
  type WithdrawStepUpChallengeResponse,
  type WithdrawStepUpMethod,
  type WithdrawStepUpVerifyResponse,
} from "./wallet";

export {
  fetchGrowthPublicSurface,
  type GrowthPublicSurfaceResponse,
  type GrowthRequestOpts,
} from "./growth";

export {
  AuthError,
  DELETE_ACCOUNT_CONFIRM_PHRASE,
  assertNoForbiddenProfileFields,
  buildStageBProfileBody,
  continuePathAfterAuth,
  deleteAuthAccount,
  fetchAuthSession,
  isAuthError,
  isKakaoOAuthReady,
  logoutAuth,
  normalizeAuthSession,
  patchAuthProfile,
  requestMagicLink,
  startKakaoOAuth,
  type AuthOnboardingStage,
  type AuthRequestOpts,
  type AuthSession,
  type DeleteAccountInput,
  type DeleteAccountResult,
  type KakaoReadyEnv,
  type KakaoStartInput,
  type KakaoStartResult,
  type LogoutResult,
  type StageBProfileInput,
  type StageBProfileResult,
} from "./auth";

export {
  ReferralError,
  bindReferral,
  fetchReferralMe,
  isReferralError,
  normalizeReferralMe,
  referralConsumerState,
  shareReferral,
  type ReferralBindInput,
  type ReferralBindResult,
  type ReferralConsumerState,
  type ReferralMe,
  type ReferralRequestOpts,
  type ReferralShareResult,
} from "./referral";

export {
  InboxError,
  fetchNotificationPrefs,
  hideInboxItem,
  isInboxError,
  listInbox,
  markInboxRead,
  normalizeInboxItem,
  normalizeInboxList,
  normalizeNotificationPrefs,
  putNotificationPrefs,
  type InboxItem,
  type InboxList,
  type InboxRequestOpts,
  type NotificationPrefs,
  type NotificationPrefsPatch,
} from "./inbox";
