/**
 * Multi-source Opportunity Creation v1 — EXECUTABLE 교차 소스 쌍만 발행.
 * EXECUTABLE != Opportunity. 프로덕션 INSERT / matcher / 새 formula 금지.
 */

const EVALUATOR_VERSION = "multi-source-opportunity.v1";

const PIPELINE_STATUS = Object.freeze({
  MULTI_SOURCE_OPPORTUNITY_CREATION: "IN_PROCESS_MEMORY",
  MULTI_SOURCE_OPPORTUNITY_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  MULTI_SOURCE_OPPORTUNITY_DB_RUNTIME: "NOT_IMPLEMENTED",
  PRODUCTION_MULTI_SOURCE_OPPORTUNITY: "NOT_IMPLEMENTED",
});

const DECISIONS = Object.freeze({
  ISSUED: "ISSUED",
  NOT_ISSUED: "NOT_ISSUED",
  INSUFFICIENT: "INSUFFICIENT",
  CONFLICT: "CONFLICT",
  BLOCKED: "BLOCKED",
});

const REASONS = Object.freeze({
  MULTI_SOURCE_EXECUTABLE: "MULTI_SOURCE_EXECUTABLE",
  SAME_SOURCE_NOT_MULTI: "SAME_SOURCE_NOT_MULTI",
  SOURCE_UNPROVEN: "SOURCE_UNPROVEN",
  PRICING_REUSE_MISMATCH: "PRICING_REUSE_MISMATCH",
  NOT_EXECUTABLE: "NOT_EXECUTABLE",
});

const BOUNDARIES = Object.freeze({
  MATCH_EQUALS_OPPORTUNITY: false,
  PROMOTABLE_EQUALS_OPPORTUNITY: false,
  EXECUTABLE_EQUALS_OPPORTUNITY: false,
  OBSERVED_PRICE_EQUALS_EXECUTABLE_PRICE: false,
  STALE_PRICE_EQUALS_CURRENT_PRICE: false,
  CANONICAL_PRODUCT_EQUALS_ASSET: false,
  NEW_PRICING_FORMULA: "FORBIDDEN",
  NEW_FX_FORMULA: "FORBIDDEN",
  NEW_MARKET_ID: "FORBIDDEN",
  NEW_FEE_TABLE: "FORBIDDEN",
  CHEAPEST_AS_BUY_LEG: "FORBIDDEN",
  SOURCE_EBAY_DEFAULTS_TO_EBAY_US: "FORBIDDEN",
  SAME_PHYSICAL_ITEM_NEVER_INFERRED: true,
  PRODUCTION_INSERT_THIS_SLICE: "FORBIDDEN",
});

const FORMULA_OWNERS = Object.freeze({
  economics: "services/market-intelligence/src/executable-economics",
  pricing: "services/market-intelligence/src/pricing-formula.cjs",
  fx: "services/market-intelligence/src/fx-snapshot-formula.cjs",
  staleAsOf: "services/api-nest/src/opportunities/opportunity-reprice.service.ts",
});

const EXECUTABLE_IS_NOT_OPPORTUNITY = true;
const DOES_NOT_INSERT_PRODUCTION_OPPORTUNITY = true;

module.exports = {
  EVALUATOR_VERSION,
  PIPELINE_STATUS,
  DECISIONS,
  REASONS,
  BOUNDARIES,
  FORMULA_OWNERS,
  EXECUTABLE_IS_NOT_OPPORTUNITY,
  DOES_NOT_INSERT_PRODUCTION_OPPORTUNITY,
};
