/**
 * @aipo/ai-platform — L1/L2 · AI PICK · AI_LOG · Eval Gate · Personal AI §47
 * L3 money execution FORBIDDEN
 * CI: verify:ai-feature-platform · verify:twin-fact-separation · verify:no-ai-data-in-git
 */

"use strict";

const {
  AI_LEVELS,
  LEVEL_POLICY,
  FORBIDDEN_L3_MONEY_ACTIONS,
  isAiLevel,
  isForbiddenMoneyAction,
  assertNoL3Money,
  assertL1NoMoney,
} = require("./levels.cjs");
const {
  AI_PICK_FORMULA_ID,
  AI_PICK_THRESHOLD,
  SCORE_WEIGHTS,
  scoreAiPick,
  applyAiPickToCard,
} = require("./ai-pick.cjs");
const {
  LANES,
  PROVIDER_IDS,
  ANSWER_PATHS,
  GUARD_STATUSES,
  buildAiLogRecord,
  toAiLogsRow,
} = require("./ai-log.cjs");
const {
  AUTO_LEARNING_ENABLED,
  EVAL_THRESHOLDS,
  evaluateModelCandidate,
  promoteToProd,
} = require("./eval-gate.cjs");
const {
  FACT_TOOLS,
  isFactTool,
  toolsForLane,
  assertToolsAllowedForLane,
} = require("./fact-tools.cjs");
const {
  FACT_SOURCES,
  DEFAULT_MIN_CONFIDENCE,
  buildFactCard,
  isFactFresh,
  partitionFreshness,
  assertFactsFreshOrThrow,
} = require("./fact-card-loader.cjs");
const {
  FORBIDDEN_TWIN_MONEY_KEYS,
  FORBIDDEN_ANSWER_PATTERNS,
  FAKE_TOOL_RESULT_PATTERNS,
  META_EXPOSURE_MARKERS,
  guardAnswer,
  userIntentAuthorizesPlatformMoney,
  isTerminalScopeRedirect,
  mayEscalateToPlatformFacts,
} = require("./answer-guard.cjs");
const {
  classifyLane,
  answerPathForLane,
  routeAssistant,
  S_PATTERNS,
  P_PATTERNS,
  EXECUTION_PATTERNS,
  OFF_TOPIC_PATTERNS,
  SCOPE_ASSURANCE,
  defaultToolsForText,
  matchesExecutionIntent,
  matchesOffTopic,
  decideScope,
} = require("./assistant-router.cjs");
const {
  HELP_CHUNK_KINDS,
  buildHelpChunk,
  rankHelpChunks,
} = require("./help-rag.cjs");
const {
  createLlmAdapter,
  llmAdapterChat,
} = require("./llm-adapter.cjs");
const {
  quotaKeyRpm,
  quotaKeyRpd,
  isSoftQuotaExceeded,
  shouldDegradeForQuota,
  G_BUSY_TEMPLATE,
  degradeAnswerPath,
  assertProviderId,
} = require("./llm-quota.cjs");
const {
  SYSTEM_BASE,
  buildCoachMessages,
  shouldCallLlm,
} = require("./coach-prompt.cjs");
const {
  S_REFUSE_TEMPLATE,
  P_REFRESH_TEMPLATE,
  P_UNAVAILABLE_TEMPLATE,
  SCOPE_REDIRECT_TEMPLATE,
  CS_DEEP_LINK,
  FACT_CHIPS,
  shapeByTone,
  renderFactAnswer,
  pickChips,
} = require("./coach-templates.cjs");
const {
  MAX_TURNS,
  MAX_TURN_TEXT_LEN,
  sanitizeTurnText,
  newConversationId,
  conversationStateRedisKey,
  buildConversationState,
  appendTurn,
  rememberResultRef,
  assertStateOwnership,
  isWithinAbsoluteLifetime,
  effectiveTtlSec,
  buildHistoryMessages,
} = require("./conversation-state.cjs");
const {
  RESULT_REF_TYPES,
  RESOLUTION_STATUSES,
  MAX_RESULT_REF_SETS,
  MAX_IDS_PER_REF,
  normalizeResultRef,
  normalizeResultRefs,
  upsertResultRef,
  extractResultRefFromFacts,
  hasReferenceCue,
  resolveResultReference,
  referencePromptBlock,
} = require("./reference-resolver.cjs");
const {
  SERVER_DERIVED_ALLOWLIST,
  ALLOWED_DERIVATION_IDS,
  NUMERIC_KINDS,
  AVAILABILITIES,
  CURRENCY_FIELDS,
  QUANTITY_FIELDS,
  PERCENT_FIELDS,
  DATE_FIELDS,
  tagServerDerived,
  assertServerDerivedAllowlist,
  collectGroundedNumerics,
  buildGroundedNumericContext,
  extractNumericClaims,
  classifyNumericClaim,
  groundAnswerNumerics,
  isForbiddenDerivedRoi,
} = require("./numeric-grounding.cjs");

module.exports = {
  AI_LEVELS,
  LEVEL_POLICY,
  FORBIDDEN_L3_MONEY_ACTIONS,
  isAiLevel,
  isForbiddenMoneyAction,
  assertNoL3Money,
  assertL1NoMoney,
  AI_PICK_FORMULA_ID,
  AI_PICK_THRESHOLD,
  SCORE_WEIGHTS,
  scoreAiPick,
  applyAiPickToCard,
  LANES,
  PROVIDER_IDS,
  ANSWER_PATHS,
  GUARD_STATUSES,
  buildAiLogRecord,
  toAiLogsRow,
  AUTO_LEARNING_ENABLED,
  EVAL_THRESHOLDS,
  evaluateModelCandidate,
  promoteToProd,
  FACT_TOOLS,
  isFactTool,
  toolsForLane,
  assertToolsAllowedForLane,
  FACT_SOURCES,
  DEFAULT_MIN_CONFIDENCE,
  buildFactCard,
  isFactFresh,
  partitionFreshness,
  assertFactsFreshOrThrow,
  FORBIDDEN_TWIN_MONEY_KEYS,
  FORBIDDEN_ANSWER_PATTERNS,
  FAKE_TOOL_RESULT_PATTERNS,
  META_EXPOSURE_MARKERS,
  guardAnswer,
  userIntentAuthorizesPlatformMoney,
  isTerminalScopeRedirect,
  mayEscalateToPlatformFacts,
  classifyLane,
  answerPathForLane,
  routeAssistant,
  S_PATTERNS,
  P_PATTERNS,
  EXECUTION_PATTERNS,
  OFF_TOPIC_PATTERNS,
  SCOPE_ASSURANCE,
  defaultToolsForText,
  matchesExecutionIntent,
  matchesOffTopic,
  decideScope,
  HELP_CHUNK_KINDS,
  buildHelpChunk,
  rankHelpChunks,
  createLlmAdapter,
  llmAdapterChat,
  quotaKeyRpm,
  quotaKeyRpd,
  isSoftQuotaExceeded,
  shouldDegradeForQuota,
  G_BUSY_TEMPLATE,
  degradeAnswerPath,
  assertProviderId,
  SYSTEM_BASE,
  buildCoachMessages,
  shouldCallLlm,
  S_REFUSE_TEMPLATE,
  P_REFRESH_TEMPLATE,
  P_UNAVAILABLE_TEMPLATE,
  SCOPE_REDIRECT_TEMPLATE,
  CS_DEEP_LINK,
  FACT_CHIPS,
  shapeByTone,
  renderFactAnswer,
  pickChips,
  MAX_TURNS,
  MAX_TURN_TEXT_LEN,
  sanitizeTurnText,
  newConversationId,
  conversationStateRedisKey,
  buildConversationState,
  appendTurn,
  rememberResultRef,
  assertStateOwnership,
  isWithinAbsoluteLifetime,
  effectiveTtlSec,
  buildHistoryMessages,
  RESULT_REF_TYPES,
  RESOLUTION_STATUSES,
  MAX_RESULT_REF_SETS,
  MAX_IDS_PER_REF,
  normalizeResultRef,
  normalizeResultRefs,
  upsertResultRef,
  extractResultRefFromFacts,
  hasReferenceCue,
  resolveResultReference,
  referencePromptBlock,
  SERVER_DERIVED_ALLOWLIST,
  ALLOWED_DERIVATION_IDS,
  NUMERIC_KINDS,
  AVAILABILITIES,
  CURRENCY_FIELDS,
  QUANTITY_FIELDS,
  PERCENT_FIELDS,
  DATE_FIELDS,
  tagServerDerived,
  assertServerDerivedAllowlist,
  collectGroundedNumerics,
  buildGroundedNumericContext,
  extractNumericClaims,
  classifyNumericClaim,
  groundAnswerNumerics,
  isForbiddenDerivedRoi,
};
