/**
 * Listing / Variant Compatibility v1 — Opportunity 전 필수 게이트.
 * SAME_CANONICAL_PRODUCT != SAME_VARIANT != TRADABLE_EQUIVALENT != SAME_PHYSICAL_ITEM.
 * matcher / Candidate Generation / Money / durable DB 권위를 바꾸지 않는다.
 */

const EVALUATOR_VERSION = "listing-variant-compatibility.v1";

const PIPELINE_STATUS = Object.freeze({
  LISTING_VARIANT_COMPATIBILITY: "IN_PROCESS_MEMORY",
  LISTING_VARIANT_COMPATIBILITY_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  LISTING_VARIANT_COMPATIBILITY_DB_RUNTIME: "NOT_IMPLEMENTED",
  PRODUCTION_LISTING_VARIANT_COMPATIBILITY: "NOT_IMPLEMENTED",
  LISTING_PROMOTION: "NOT_IMPLEMENTED",
  MULTI_SOURCE_OPPORTUNITY_CREATION: "NOT_IMPLEMENTED",
});

const DECISIONS = Object.freeze({
  COMPATIBLE: "COMPATIBLE",
  INCOMPATIBLE: "INCOMPATIBLE",
  INSUFFICIENT: "INSUFFICIENT",
  CONFLICT: "CONFLICT",
  BLOCKED: "BLOCKED",
});

const REASONS = Object.freeze({
  SAME_VARIANT_EXACT: "SAME_VARIANT_EXACT",
  NOT_SAME_VARIANT: "NOT_SAME_VARIANT",
  VARIANT_FIELD_MISSING: "VARIANT_FIELD_MISSING",
  IDENTITY_KEY_INCOMPLETE: "IDENTITY_KEY_INCOMPLETE",
  IDENTITY_KEY_MISMATCH: "IDENTITY_KEY_MISMATCH",
  CANONICAL_PRODUCT_MISMATCH: "CANONICAL_PRODUCT_MISMATCH",
  SAME_SOURCE: "SAME_SOURCE",
  SAME_LISTING: "SAME_LISTING",
  PROFILE_CONFLICT: "PROFILE_CONFLICT",
  PROFILE_DEFERRED: "PROFILE_DEFERRED",
  PROFILE_UNSUPPORTED: "PROFILE_UNSUPPORTED",
  INELIGIBLE_OBSERVATION: "INELIGIBLE_OBSERVATION",
});

const BOUNDARIES = Object.freeze({
  SAME_CANONICAL_PRODUCT_EQUALS_SAME_VARIANT: false,
  SAME_VARIANT_EQUALS_SAME_PHYSICAL_ITEM: false,
  SAME_PHYSICAL_ITEM_NEVER_INFERRED: true,
  TRADABLE_EQUIVALENT_REQUIRES_SAME_VARIANT: true,
  TRADABLE_EQUIVALENT_REQUIRES_CROSS_SOURCE: true,
  CONDITION_IS_LISTING_NOT_IDENTITY: true,
  PRICE_AS_COMPATIBILITY: "FORBIDDEN",
  TITLE_AS_COMPATIBILITY_OWNER: "FORBIDDEN",
  IMAGE_AS_COMPATIBILITY_OWNER: "FORBIDDEN",
  MVP_OPPORTUNITY_REQUIRES_GRADE_EQUIVALENT: true,
});

module.exports = {
  EVALUATOR_VERSION,
  PIPELINE_STATUS,
  DECISIONS,
  REASONS,
  BOUNDARIES,
};
