/**
 * Money §49.9 full catalog — P1~P24 (abuse) · E1~E12 (error/defect).
 * Executable guards live in sibling p49_*.ts · this file = SSOT matrix.
 */

import type { RiskRuleDef } from "../risk.types";

export const P49_ABUSE_RULES: readonly RiskRuleDef[] = [
  {
    code: "P1",
    kind: "abuse",
    title: "practice→profit 승격 시도",
    defense: "practice 출금/merge/participate 코드경로 0",
    detect: "403 PRACTICE_NOT_WITHDRAWABLE",
    severity: "high",
    toastCode: "PRACTICE_NOT_WITHDRAWABLE",
  },
  {
    code: "P2",
    kind: "abuse",
    title: "G4 demo/ticker 금액을 profit로 인출",
    defense: "demo≠ledger · CountUp/profit credit=settlement only",
    detect: "recon + audit",
    severity: "high",
  },
  {
    code: "P3",
    kind: "abuse",
    title: "연출 완료만으로 profit +",
    defense: "presentation 타이머≠credit",
    detect: "verify:presentation-cannot-credit",
    severity: "high",
  },
  {
    code: "P4",
    kind: "abuse",
    title: "profit 상한 초과 출금",
    defense: "서버 bucket FOR UPDATE 상한",
    detect: "INSUFFICIENT_PROFIT",
    severity: "warn",
    toastCode: "INSUFFICIENT_PROFIT",
  },
  {
    code: "P5",
    kind: "abuse",
    title: "locked 포함 출금",
    defense: "locked 제외 가용만",
    detect: "reject",
    severity: "warn",
    toastCode: "INSUFFICIENT_PROFIT",
  },
  {
    code: "P6",
    kind: "abuse",
    title: "확인 시트 우회 principal 출금",
    defense: "principalConfirmToken 필수",
    detect: "403 PRINCIPAL_CONFIRM_REQUIRED",
    severity: "high",
    toastCode: "WITHDRAW_PRINCIPAL_WARN",
  },
  {
    code: "P7",
    kind: "abuse",
    title: "원금 출금 후 즉시 고액 기회 슬롯 점유",
    defense: "participate는 현재 principal 기준",
    detect: "기회 잠금",
    severity: "info",
  },
  {
    code: "P8",
    kind: "abuse",
    title: "입금→즉시 전액 원금출금 wash",
    defense: "§11.2 minHoldingHours · profit-only 제외",
    detect: "MIN_HOLDING risk",
    severity: "high",
    toastCode: "MIN_HOLDING",
  },
  {
    code: "P9",
    kind: "abuse",
    title: "수익출금 스팸",
    defense: "rate limit + idempotency_key",
    detect: "429 RATE_LIMITED",
    severity: "warn",
    toastCode: "RATE_LIMITED",
  },
  {
    code: "P10",
    kind: "abuse",
    title: "다계정 유지보너스 파밍",
    defense: "device graph · 보너스 per-KYC",
    detect: "§42+risk signal",
    severity: "high",
    freezeOnHit: true,
  },
  {
    code: "P11",
    kind: "abuse",
    title: "추천인 연습잔액 현금화",
    defense: "practice non-withdrawable (=P1)",
    detect: "PRACTICE_NOT_WITHDRAWABLE",
    severity: "high",
    toastCode: "PRACTICE_NOT_WITHDRAWABLE",
  },
  {
    code: "P12",
    kind: "abuse",
    title: "Admin 조정으로 버킷 조작 은닉",
    defense: "버킷 지정+reason+RBAC+audit",
    detect: "§37 admin_adjust",
    severity: "high",
  },
  {
    code: "P13",
    kind: "abuse",
    title: "이중 출금 레이스",
    defense: "idempotency UNIQUE + row lock",
    detect: "409 silent dup",
    severity: "high",
  },
  {
    code: "P14",
    kind: "abuse",
    title: "settlement와 출금 레이스",
    defense: "동일 계정 ASC FOR UPDATE · settle→withdraw",
    detect: "ledger lock order",
    severity: "high",
  },
  {
    code: "P15",
    kind: "abuse",
    title: "merge와 출금 레이스",
    defense: "동일 락 · merge idempotency",
    detect: "ledger",
    severity: "high",
  },
  {
    code: "P16",
    kind: "abuse",
    title: "환율로 KRW 수익 부풀려 출금",
    defense: "USDT ledger truth · KRW snapshot",
    detect: "§11",
    severity: "warn",
  },
  {
    code: "P17",
    kind: "abuse",
    title: "원화 입금 미확정 상태 profit 취급",
    defense: "credit after confirm only",
    detect: "§41",
    severity: "high",
  },
  {
    code: "P18",
    kind: "abuse",
    title: "chargeback 후 수익만 빼기",
    defense: "KRW 출금 Admin · freeze path",
    detect: "A14 freeze",
    severity: "p0",
    freezeOnHit: true,
    toastCode: "ACCOUNT_FROZEN",
  },
  {
    code: "P19",
    kind: "abuse",
    title: "제재 주소로 수익 출금",
    defense: "sanctions screen",
    detect: "A7",
    severity: "p0",
    freezeOnHit: true,
  },
  {
    code: "P20",
    kind: "abuse",
    title: "UI만 버킷 조작 (클라 변조)",
    defense: "서버 재계산 · 클라 금액 trust 0",
    detect: "api recompute",
    severity: "warn",
  },
  {
    code: "P21",
    kind: "abuse",
    title: "원금 잠금 사칭 고객센터 유도",
    defense: "인앱 원금출금 경로 E2E 게이트",
    detect: "verify:principal-withdraw-reachable",
    severity: "info",
  },
  {
    code: "P22",
    kind: "abuse",
    title: "수익 몰수 위협 카피",
    defense: "copy CI 금지어",
    detect: "verify:korean-ui / abuse copy scan",
    severity: "warn",
  },
  {
    code: "P23",
    kind: "abuse",
    title: "Sybil로 소액 수익 반복 출금",
    defense: "KYC·velocity·device",
    detect: "risk velocity",
    severity: "high",
    freezeOnHit: true,
  },
  {
    code: "P24",
    kind: "abuse",
    title: "bucket drift 고의 유발",
    defense: "recon job · mismatch=CIRCUIT",
    detect: "money.circuit.bucket_invariant CIRCUIT",
    severity: "p0",
    freezeOnHit: true,
    toastCode: "CIRCUIT_OPEN",
  },
] as const;

export const P49_ERROR_RULES: readonly RiskRuleDef[] = [
  {
    code: "E1",
    kind: "error",
    title: "버킷 합 ≠ liability",
    defense: "money ops halt + CIRCUIT",
    detect: "money.circuit.bucket_invariant P0",
    severity: "p0",
    freezeOnHit: true,
    toastCode: "money.circuit.bucket_invariant",
  },
  {
    code: "E2",
    kind: "error",
    title: "출금 기본이 principal로 열림",
    defense: "verify:withdraw-mode-default FAIL build",
    detect: "CI",
    severity: "high",
  },
  {
    code: "E3",
    kind: "error",
    title: "원금 출금 CTA 없음/숨김",
    defense: "verify:principal-withdraw-reachable FAIL",
    detect: "CI",
    severity: "high",
  },
  {
    code: "E4",
    kind: "error",
    title: "성공 화면 3CTA 누락",
    defense: "verify:execution-surfaces FAIL",
    detect: "CI",
    severity: "warn",
  },
  {
    code: "E5",
    kind: "error",
    title: "settlement가 principal에 유저수익 기입",
    defense: "recon fail · shadow",
    detect: "settlement-profit-only",
    severity: "p0",
  },
  {
    code: "E6",
    kind: "error",
    title: "safe_stop 후 locked 미해제",
    defense: "auto unlock job + alert",
    detect: "risk signal",
    severity: "high",
  },
  {
    code: "E7",
    kind: "error",
    title: "merge 부분 실패",
    defense: "트랜잭션 atomic",
    detect: "toast 재시도",
    severity: "warn",
  },
  {
    code: "E8",
    kind: "error",
    title: "출금 중 앱 종료",
    defense: "intent status machine 복구",
    detect: "pending resume",
    severity: "info",
  },
  {
    code: "E9",
    kind: "error",
    title: "FX 표시 오차",
    defense: "≈표기+snapshot · 출금 USDT only",
    detect: "P16 sibling",
    severity: "warn",
  },
  {
    code: "E10",
    kind: "error",
    title: "토스트 중복",
    defense: "single-flight · UNIQUE source_event",
    detect: "push dedup",
    severity: "info",
  },
  {
    code: "E11",
    kind: "error",
    title: "오프라인 출금 큐잉",
    defense: "NETWORK_ERROR · 큐 금지",
    detect: "§23 money ops",
    severity: "warn",
    toastCode: "NETWORK_ERROR",
  },
  {
    code: "E12",
    kind: "error",
    title: "Admin 버킷 미지정 조정",
    defense: "API 400 · UI block",
    detect: "bucket required",
    severity: "high",
  },
] as const;

export const P49_ALL_RULES: readonly RiskRuleDef[] = [
  ...P49_ABUSE_RULES,
  ...P49_ERROR_RULES,
];

export const P49_RULE_CODES = P49_ALL_RULES.map((r) => r.code);

export function getP49Rule(code: string): RiskRuleDef | undefined {
  return P49_ALL_RULES.find((r) => r.code === code);
}

/** Forbidden user-facing copy fragments (P22 / E threat copy) */
export const P49_FORBIDDEN_COPY = [
  "몰수",
  "원금잠금영구",
  "원금 영구 잠금",
  "수익 몰수",
  "강제 몰수",
] as const;
