/**
 * /profits Desktop visual fixture.
 * owner = visual_fixture. production `/profits` fallback으로 쓰지 않음.
 * duration owner 없음 → null(—). 환율 곱셈 없음.
 */

import { SPARK_DASH_DESKTOP_VISUAL_FIXTURE } from "../spark-dash-home/visual-fixture";
import type { ProfitsDesktopModel, ProfitsOpportunity } from "./types";

export const PROFITS_FIXTURE_OWNER = "visual_fixture" as const;

const items: ProfitsOpportunity[] = [
  {
    id: "fixture-nike",
    partner: "eBay",
    partnerKind: "ebay",
    title: "Nike Air Force 1 '07",
    productMediaUrl: "/spark-dash/product-sneaker-hero.png",
    productMediaAlt: "Nike Air Force 1 '07",
    mediaState: "AVAILABLE",
    ratePct: "28.4%",
    expectedProfitUsdt: "+284.00 USDT",
    expectedProfitKrw: "≈ ₩386,240",
    durationLabel: null,
    capitalUsdt: "1,000 USDT",
    capitalKrw: "≈ ₩1,360,000",
    statusLabel: "참여 가능",
    href: "/profits/fixture-nike",
    official: true,
    joinable: true,
    featured: true,
  },
  {
    id: "fixture-ps5",
    partner: "Amazon",
    partnerKind: "amazon",
    title: "PlayStation 5",
    productMediaUrl: null,
    productMediaAlt: "PlayStation 5",
    mediaState: "MISSING",
    ratePct: "27.7%",
    expectedProfitUsdt: "+346.25 USDT",
    expectedProfitKrw: "≈ ₩470,900",
    durationLabel: null,
    capitalUsdt: "1,250 USDT",
    capitalKrw: "≈ ₩1,700,000",
    statusLabel: "조건 확인 후 참여 가능",
    href: "/profits/fixture-ps5",
    official: true,
    joinable: false,
    featured: false,
  },
  {
    id: "fixture-iphone",
    partner: "Yahoo! JAPAN Auction",
    partnerKind: "yahoo",
    title: "iPhone 15 Pro",
    productMediaUrl: null,
    productMediaAlt: "iPhone 15 Pro",
    mediaState: "MISSING",
    ratePct: "24.3%",
    expectedProfitUsdt: "+267.30 USDT",
    expectedProfitKrw: "≈ ₩363,528",
    durationLabel: null,
    capitalUsdt: "1,100 USDT",
    capitalKrw: "≈ ₩1,496,000",
    statusLabel: "조건 확인 후 참여 가능",
    href: "/profits/fixture-iphone",
    official: true,
    joinable: false,
    featured: false,
  },
  {
    id: "fixture-airpods",
    partner: "eBay",
    partnerKind: "ebay",
    title: "AirPods Pro 2",
    productMediaUrl: null,
    productMediaAlt: "AirPods Pro 2",
    mediaState: "MISSING",
    ratePct: "26.1%",
    expectedProfitUsdt: "+234.90 USDT",
    expectedProfitKrw: "≈ ₩319,464",
    durationLabel: null,
    capitalUsdt: "900 USDT",
    capitalKrw: "≈ ₩1,224,000",
    statusLabel: "조건 확인 후 참여 가능",
    href: "/profits/fixture-airpods",
    official: true,
    joinable: false,
    featured: false,
  },
  {
    id: "fixture-switch",
    partner: "Amazon Japan",
    partnerKind: "amazon",
    title: "Nintendo Switch",
    productMediaUrl: null,
    productMediaAlt: "Nintendo Switch",
    mediaState: "MISSING",
    ratePct: "23.8%",
    expectedProfitUsdt: "+226.10 USDT",
    expectedProfitKrw: "≈ ₩307,496",
    durationLabel: null,
    capitalUsdt: "950 USDT",
    capitalKrw: "≈ ₩1,292,000",
    statusLabel: "조건 확인 후 참여 가능",
    href: "/profits/fixture-switch",
    official: true,
    joinable: false,
    featured: false,
  },
];

export const PROFITS_DESKTOP_VISUAL_FIXTURE: ProfitsDesktopModel = {
  owner: PROFITS_FIXTURE_OWNER,
  viewState: "READY",
  displayName: SPARK_DASH_DESKTOP_VISUAL_FIXTURE.displayName,
  levelLabel: SPARK_DASH_DESKTOP_VISUAL_FIXTURE.levelLabel,
  sidebarBalance: SPARK_DASH_DESKTOP_VISUAL_FIXTURE.sidebarBalance,
  nav: SPARK_DASH_DESKTOP_VISUAL_FIXTURE.nav,
  items,
};
