/**
 * Candidate Generation v1 — 후보 쌍 탐색 첫 슬라이스.
 * Candidate != MATCH != Listing != Opportunity.
 * matcher / Money / durable DB 권위를 바꾸지 않는다.
 */

const GENERATOR_VERSION = "candidate-generation.v1";

const PIPELINE_STATUS = Object.freeze({
  CANDIDATE_GENERATION: "IN_PROCESS_MEMORY",
  CANDIDATE_GENERATION_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  CANDIDATE_GENERATION_DB_RUNTIME: "NOT_IMPLEMENTED",
  PRODUCTION_CANDIDATE_GENERATION: "NOT_IMPLEMENTED",
  IMAGE_CANDIDATE_DISCOVERY: "NOT_IMPLEMENTED",
  LISTING_VARIANT_COMPATIBILITY: "NOT_IMPLEMENTED",
  LISTING_PROMOTION: "NOT_IMPLEMENTED",
  MULTI_SOURCE_OPPORTUNITY_CREATION: "NOT_IMPLEMENTED",
});

const CANDIDATE_IS_NOT_MATCH_TRUTH = true;
const CANDIDATE_IS_NOT_OPPORTUNITY = true;
const CROSS_SOURCE_ONLY = true;

const REASONS = Object.freeze({
  TYPED_IDENTIFIER_EXACT: "TYPED_IDENTIFIER_EXACT",
  CATEGORY_NATIVE_OWNER_EXACT: "CATEGORY_NATIVE_OWNER_EXACT",
  OWNER_ANCHORED_TITLE: "OWNER_ANCHORED_TITLE",
});

const SKIP_REASONS = Object.freeze({
  SAME_OBSERVATION: "SAME_OBSERVATION",
  SAME_SOURCE: "SAME_SOURCE",
  INELIGIBLE: "INELIGIBLE",
  PROFILE_CONFLICT: "PROFILE_CONFLICT",
  PROFILE_DEFERRED: "PROFILE_DEFERRED",
  PROFILE_UNSUPPORTED: "PROFILE_UNSUPPORTED",
  NO_SHARED_BLOCKING_KEY: "NO_SHARED_BLOCKING_KEY",
  BRAND_CONFLICT: "BRAND_CONFLICT",
});

const FORBIDDEN_BLOCKING_FAMILIES = Object.freeze([
  "title",
  "image",
  "imageUrl",
  "price",
  "nativeAmount",
  "externalItemId",
  "fashionphileSku",
  "epid",
  "chrono24ProductId",
]);

module.exports = {
  GENERATOR_VERSION,
  PIPELINE_STATUS,
  CANDIDATE_IS_NOT_MATCH_TRUTH,
  CANDIDATE_IS_NOT_OPPORTUNITY,
  CROSS_SOURCE_ONLY,
  REASONS,
  SKIP_REASONS,
  FORBIDDEN_BLOCKING_FAMILIES,
};
