/**
 * Thin typed bridge to @aipo/market-intelligence (CJS SSOT).
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const mi = require("@aipo/market-intelligence") as typeof import("@aipo/market-intelligence");

export const {
  MARKET_IDS,
  MARKET_LABEL_KO,
  CAPITAL_BANDS,
  CAPITAL_BAND_LABEL_KO,
  CAPITAL_FILTER_CHIPS,
  CATEGORY_FILTER_CHIPS,
  SEED_RATIO_LOCK,
  DEFAULT_FEE_PCT,
  DEFAULT_PLATFORM_MARGIN_PCT,
  PIPELINE_STAGES,
  FORBIDDEN_MARKET_IDS,
  FORBIDDEN_ADAPTER_IDS,
  computeOpportunityPricing,
  composeFxSnapshot,
  approxKrwFromSnapshot,
  normalizeAssetMaster,
  isImageMissing,
  resolveAssetImage,
  canAutoPublishAvailable,
  assertPublishImageGuard,
  assertCategoryImageSource,
  assertSkuImageOneToOne,
  assetIconForCategory,
  toOpportunityImageProjection,
  ASSET_ICON_BY_CATEGORY,
  resolveCapitalBand,
  isCapitalBand,
  capitalBandLabelKo,
  capitalBandAtMost,
  assertCatalogSeedRatios,
  isForbiddenMarketId,
  assertNotForbidden,
  feePctForMarket,
  withinTolerance,
  FX_FORMULA_IDS,
  IMAGE_RIGHTS_NOTE_KO,
  ASSET_CATEGORIES,
  extractGradeFromText,
  evaluateListingGradeMatch,
  evaluateCardListingMatch,
  buildCardMatchKey,
  listTradingCardSeeds,
  tradingCardSeedsAsAssetMasters,
  assertTradingCardSeedInvariants,
  TRADING_CARD_SEEDS,
  evaluateBagListingMatch,
  buildBagMatchKey,
  listLuxuryBagSeeds,
  luxuryBagSeedsAsAssetMasters,
  assertLuxuryBagSeedInvariants,
  LUXURY_BAG_SEEDS,
  evaluateWatchListingMatch,
  buildWatchMatchKey,
  listWatchSeeds,
  watchSeedsAsAssetMasters,
  assertWatchSeedInvariants,
  assertDay1CatalogCoexistence,
  isWhaleCapitalPath,
  isUltraWatchWhalePath,
  WHALE_MIN_REQUIRED_CAPITAL_USDT,
  WATCH_SEEDS,
  ARBITRAGE_TYPES,
  ARBITRAGE_TYPE_LABEL_KO,
  V1_FEED_ARBITRAGE_TYPES,
  DEFAULT_TIME_SENSITIVE_HORIZON_SEC,
  SELL_SUCCESS_WINDOW_DAYS_DEFAULT,
  FX_USES_OPPORTUNITY_CARD_SCHEMA,
  arbitrageTypeKo,
  isV1FeedArbitrageType,
  projectOpportunityScanFields,
  withTimeSensitiveTag,
  shouldTagTimeSensitive,
  projectSellSuccessMeta,
  assertAvailableScanProjection,
  assertAvailableCardsArbitrageTypeKo,
  assertFxUsesSameCardSchema,
  INTERNAL_TO_USER_FIELD,
  USER_SURFACE_STRIP_KEYS,
  WAITING_FACT_SOURCES,
  USER_BANNED_TRADER_JARGON,
  projectWaitingFacts,
  projectCapitalProviderUserSurface,
  assertUserSurfaceCapitalProvider,
  assertCapitalProviderProjectionInvariants,
  userExecutionModeHint,
  CLASSIFICATION_OWNER,
  FEED_BUCKETS,
  SUGGEST_TICK_USDT,
  NEAR_MISS_CAP_FLOOR_USDT,
  NEAR_MISS_CAP_PRINCIPAL_PCT,
  ceilToTick,
  computeSuggestDepositUsdt,
  resolveNearMissCapUsdt,
  classifyAffordability,
  compareBalanceAwareFeedItems,
  projectBalanceAwareCard,
  buildBalanceAwareFeed,
  nearMissCapFromExecutionPolicy,
  DAY1_FX_SNAPSHOT_ID,
  DAY1_USDT_KRW,
  FORBIDDEN_INGEST_ADAPTERS,
  day1FxSnapshot,
  listDay1AssetMasters,
  assertDay1ListingLeg,
  buildEbayIngestListing,
  buildRuntimeSeedBundleForAsset,
  buildMinCatalogRuntimeSeed,
  normalizeIngestListingsForPersist,
  SUPPORTED_MARKETPLACE_FIAT_CURRENCIES,
  SUPPORTED_NATIVE_CURRENCIES,
  FIAT_USD_RATE_FIELD,
  deriveMarketplaceLegs,
  normalizeNativeToUsdt,
  resolveStoredLegListingPrices,
} = mi;

export type PricingResult = ReturnType<typeof computeOpportunityPricing>;
export type FxSnapshotResult = ReturnType<typeof composeFxSnapshot>;
export type FxMarketplaceLegs = ReturnType<typeof deriveMarketplaceLegs>;
export type FxNormalizeResult = ReturnType<typeof normalizeNativeToUsdt>;
export type StoredLegListingResolve = ReturnType<
  typeof resolveStoredLegListingPrices
>;
