/**
 * CanonicalProduct in-process 계약.
 * matcher / identity-matching.v2 권위를 바꾸지 않는다.
 * MATCH 이후에만 생성. durable DB 주장 금지.
 */

const PIPELINE_STATUS = Object.freeze({
  CANONICAL_PRODUCT_RUNTIME: "IN_PROCESS_MEMORY",
  CANONICAL_PRODUCT_DURABLE_DB_PERSISTENCE: "NOT_IMPLEMENTED",
  CANONICAL_PRODUCT_SOURCE_LINK_DB_RUNTIME: "NOT_IMPLEMENTED",
  PUTDUK_PRODUCT_ID_STABLE: "PASS_IN_PROCESS_ONLY",
  PUTDUK_PRODUCT_ID_STABLE_WITHIN_REPOSITORY_LIFETIME: "PASS",
  PUTDUK_PRODUCT_ID_DURABLE_STABILITY: "NOT_IMPLEMENTED",
  MATCH_RESULT_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  GENERIC_PRODUCT_PROFILE: "PASS",
  CANDIDATE_GENERATION: "NOT_IMPLEMENTED",
});

const CREATE_ONLY_AFTER_MATCH = true;
const PUTDUK_PRODUCT_ID_EQUALS_MATCH_EVIDENCE = "NO";
const SAME_CANONICAL_PRODUCT_EQUALS_SAME_PHYSICAL_ITEM = "NO";
const SOURCE_OBSERVATION_MULTI_CANONICAL_ATTACHMENT = "BLOCKED";

const PD_PREFIX = "PD-";
const PD_DIGITS = 7;
const CANONICAL_PRODUCT_ID_PREFIX = "cp_";

const FORBIDDEN_SOURCE_ID_FRAGMENTS = Object.freeze(["113669", "377416817781"]);

const FORBIDDEN_IDENTITY_KEY_FIELDS = Object.freeze([
  "title",
  "image",
  "imageUrl",
  "price",
  "nativeAmount",
  "nativeCurrency",
  "nativePrice",
  "sourceItemId",
  "externalItemId",
  "observationRef",
  "latestObservationRef",
  "putdukProductCode",
  "canonicalProductId",
  "language",
  "finishOrEdition",
  "finish",
  "grade",
]);

const TRADING_CARD_IDENTITY_KEY_FIELDS = Object.freeze([
  "game",
  "set",
  "cardNumber",
  "characterOrName",
]);

const OPTIONAL_ENRICHMENT_FIELDS = Object.freeze(["language", "finishOrEdition"]);

const FORBIDDEN_ON_LINK = Object.freeze([
  "nativePrice",
  "priceSemantics",
  "observedAt",
  "availability",
  "nativeAmount",
  "nativeCurrency",
]);

const CREATE_BLOCKED = Object.freeze({
  DECISION: "CREATE_BLOCKED_DECISION",
  DISCOVERY: "CREATE_BLOCKED_DISCOVERY",
  SOURCE_STATUS: "CREATE_BLOCKED_SOURCE_STATUS",
  OBSERVATION_MISMATCH: "CREATE_BLOCKED_OBSERVATION_MISMATCH",
  IDENTITY_KEY: "IDENTITY_KEY_INCOMPLETE",
  GENERIC_PROFILE: "GENERIC_PRODUCT_PROFILE_UNSUPPORTED",
  OBSERVATION_CONFLICT: "OBSERVATION_CANONICAL_PRODUCT_CONFLICT",
  LINK_PAYLOAD_CONFLICT: "LINK_PAYLOAD_CONFLICT",
});

module.exports = {
  PIPELINE_STATUS,
  CREATE_ONLY_AFTER_MATCH,
  PUTDUK_PRODUCT_ID_EQUALS_MATCH_EVIDENCE,
  SAME_CANONICAL_PRODUCT_EQUALS_SAME_PHYSICAL_ITEM,
  SOURCE_OBSERVATION_MULTI_CANONICAL_ATTACHMENT,
  PD_PREFIX,
  PD_DIGITS,
  CANONICAL_PRODUCT_ID_PREFIX,
  FORBIDDEN_SOURCE_ID_FRAGMENTS,
  FORBIDDEN_IDENTITY_KEY_FIELDS,
  TRADING_CARD_IDENTITY_KEY_FIELDS,
  OPTIONAL_ENRICHMENT_FIELDS,
  FORBIDDEN_ON_LINK,
  CREATE_BLOCKED,
};
