/**
 * Listing Promotion Contract v1 — Listing→Opportunity 승격 계약.
 * COMPATIBLE != PROMOTABLE != Opportunity.
 * matcher / Candidate Generation / Money / durable DB 권위를 바꾸지 않는다.
 */

const PROMOTER_VERSION = "listing-promotion.v1";

const PIPELINE_STATUS = Object.freeze({
  LISTING_PROMOTION: "IN_PROCESS_MEMORY",
  LISTING_PROMOTION_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  LISTING_PROMOTION_DB_RUNTIME: "NOT_IMPLEMENTED",
  PRODUCTION_LISTING_PROMOTION: "NOT_IMPLEMENTED",
  EXECUTABLE_PRICE_AVAIL_FEES_FX: "NOT_IMPLEMENTED",
  MULTI_SOURCE_OPPORTUNITY_CREATION: "NOT_IMPLEMENTED",
});

const DECISIONS = Object.freeze({
  PROMOTABLE: "PROMOTABLE",
  NOT_PROMOTABLE: "NOT_PROMOTABLE",
  INSUFFICIENT: "INSUFFICIENT",
  CONFLICT: "CONFLICT",
  BLOCKED: "BLOCKED",
});

const REASONS = Object.freeze({
  COMPATIBLE_CANONICAL_LISTING_PAIR: "COMPATIBLE_CANONICAL_LISTING_PAIR",
  CANONICAL_PRODUCT_REQUIRED: "CANONICAL_PRODUCT_REQUIRED",
  CANONICAL_PRODUCT_MISMATCH: "CANONICAL_PRODUCT_MISMATCH",
  LISTING_IDENTITY_INCOMPLETE: "LISTING_IDENTITY_INCOMPLETE",
  NOT_TRADABLE_EQUIVALENT: "NOT_TRADABLE_EQUIVALENT",
});

const BOUNDARIES = Object.freeze({
  COMPATIBLE_EQUALS_PROMOTABLE: false,
  PROMOTABLE_EQUALS_OPPORTUNITY: false,
  CANONICAL_PRODUCT_REQUIRED_FOR_PROMOTION: true,
  OBSERVED_PRICE_EQUALS_EXECUTABLE_PRICE: false,
  STALE_PRICE_EQUALS_CURRENT_PRICE: false,
  PRICE_AS_PROMOTION: "FORBIDDEN",
  TITLE_AS_PROMOTION_OWNER: "FORBIDDEN",
  IMAGE_AS_PROMOTION_OWNER: "FORBIDDEN",
  SAME_PHYSICAL_ITEM_NEVER_INFERRED: true,
});

const LISTING_PROMOTION_IS_NOT_OPPORTUNITY = true;
const LISTING_PROMOTION_DOES_NOT_COMPUTE_EXECUTABLE_PRICE = true;

module.exports = {
  PROMOTER_VERSION,
  PIPELINE_STATUS,
  DECISIONS,
  REASONS,
  BOUNDARIES,
  LISTING_PROMOTION_IS_NOT_OPPORTUNITY,
  LISTING_PROMOTION_DOES_NOT_COMPUTE_EXECUTABLE_PRICE,
};
