export {
  AuthError,
  assertNoForbiddenProfileFields,
  buildStageBProfileBody,
  continuePathAfterAuth,
  deleteAuthAccount,
  fetchAuthSession,
  isAuthError,
  logoutAuth,
  normalizeAuthSession,
  patchAuthProfile,
  requestMagicLink,
  signupStageA,
  startKakaoOAuth,
} from "./fetch";
export { finishOauth, verifyMagicLink } from "./proof";
export {
  changePassword,
  completePasswordReset,
  findId,
  listSessions,
  loginClassic,
  logoutAllDevices,
  refreshSession,
  requestMagicLinkWithConsent,
  requestPasswordReset,
  resendSignupVerification,
  revokeSessionFamily,
  signupClassicActivate,
  signupClassicRequest,
  type ClassicSignupInput,
  type MagicLinkConsent,
  type SessionFamilySummary,
} from "./classic";
export { isKakaoOAuthReady, type KakaoReadyEnv } from "./kakao-ready";
export {
  DELETE_ACCOUNT_CONFIRM_PHRASE,
  type AuthOnboardingStage,
  type AuthRequestOpts,
  type AuthSession,
  type DeleteAccountInput,
  type DeleteAccountResult,
  type KakaoStartInput,
  type KakaoStartResult,
  type LogoutResult,
  type StageASignupInput,
  type StageBProfileInput,
  type StageBProfileResult,
} from "./types";
