export {
  AuthError,
  assertNoForbiddenProfileFields,
  buildStageBProfileBody,
  continuePathAfterAuth,
  deleteAuthAccount,
  fetchAuthSession,
  isAuthError,
  logoutAuth,
  normalizeAuthSession,
  patchAuthProfile,
  requestMagicLink,
  requestSignupMagicLink,
  verifyMagicLink,
  signupStageA,
  startKakaoOAuth,
} from "./fetch";
export { isKakaoOAuthReady, type KakaoReadyEnv } from "./kakao-ready";
export {
  DELETE_ACCOUNT_CONFIRM_PHRASE,
  type AuthOnboardingStage,
  type AuthRequestOpts,
  type AuthSession,
  type DeleteAccountInput,
  type DeleteAccountResult,
  type KakaoStartInput,
  type KakaoStartResult,
  type LogoutResult,
  type StageASignupInput,
  type StageBProfileInput,
  type StageBProfileResult,
} from "./types";
