/**
 * Executable economics v1 — price + availability + fees + FX wiring.
 * Money/Engine owner 재사용만. 새 formula / marketId / fee 표 금지.
 * PROMOTABLE != EXECUTABLE != Opportunity.
 */

const EVALUATOR_VERSION = "executable-economics.v1";

const PIPELINE_STATUS = Object.freeze({
  EXECUTABLE_PRICE_AVAIL_FEES_FX: "IN_PROCESS_MEMORY",
  EXECUTABLE_ECONOMICS_DURABLE_PERSISTENCE: "NOT_IMPLEMENTED",
  EXECUTABLE_ECONOMICS_DB_RUNTIME: "NOT_IMPLEMENTED",
  PRODUCTION_EXECUTABLE_ECONOMICS: "NOT_IMPLEMENTED",
  MULTI_SOURCE_OPPORTUNITY_CREATION: "NOT_IMPLEMENTED",
});

const DECISIONS = Object.freeze({
  EXECUTABLE: "EXECUTABLE",
  NOT_EXECUTABLE: "NOT_EXECUTABLE",
  INSUFFICIENT: "INSUFFICIENT",
  CONFLICT: "CONFLICT",
  BLOCKED: "BLOCKED",
});

const REASONS = Object.freeze({
  WIRED_DAY1_ECONOMICS: "WIRED_DAY1_ECONOMICS",
  NOT_PROMOTABLE: "NOT_PROMOTABLE",
  LEG_ASSIGNMENT_REQUIRED: "LEG_ASSIGNMENT_REQUIRED",
  LEG_ASSIGNMENT_UNKNOWN: "LEG_ASSIGNMENT_UNKNOWN",
  NATIVE_PRICE_MISSING: "NATIVE_PRICE_MISSING",
  NATIVE_PRICE_UNPROVEN: "NATIVE_PRICE_UNPROVEN",
  AVAILABILITY_UNKNOWN: "AVAILABILITY_UNKNOWN",
  AVAILABILITY_MISSING: "AVAILABILITY_MISSING",
  UNAVAILABLE: "UNAVAILABLE",
  FRESHNESS_UNPROVEN: "FRESHNESS_UNPROVEN",
  PRICE_STALE: "PRICE_STALE",
  FX_SNAPSHOT_REQUIRED: "FX_SNAPSHOT_REQUIRED",
  FX_UNSUPPORTED_CURRENCY: "FX_UNSUPPORTED_CURRENCY",
  FX_MISSING: "FX_MISSING",
  FX_INVALID: "FX_INVALID",
  FX_NORMALIZE_FAILED: "FX_NORMALIZE_FAILED",
  MARKET_ID_UNRESOLVED: "MARKET_ID_UNRESOLVED",
  MARKET_ID_NOT_DAY1: "MARKET_ID_NOT_DAY1",
  ILLEGAL_LEG_PAIR: "ILLEGAL_LEG_PAIR",
});

const BOUNDARIES = Object.freeze({
  PROMOTABLE_EQUALS_EXECUTABLE: false,
  EXECUTABLE_EQUALS_OPPORTUNITY: false,
  OBSERVED_PRICE_EQUALS_EXECUTABLE_PRICE: false,
  STALE_PRICE_EQUALS_CURRENT_PRICE: false,
  NEW_PRICING_FORMULA: "FORBIDDEN",
  NEW_FX_FORMULA: "FORBIDDEN",
  NEW_MARKET_ID: "FORBIDDEN",
  NEW_FEE_TABLE: "FORBIDDEN",
  CHEAPEST_AS_BUY_LEG: "FORBIDDEN",
  SOURCE_EBAY_DEFAULTS_TO_EBAY_US: "FORBIDDEN",
  SAME_PHYSICAL_ITEM_NEVER_INFERRED: true,
});

const FORMULA_OWNERS = Object.freeze({
  pricing: "services/market-intelligence/src/pricing-formula.cjs",
  fx: "services/market-intelligence/src/fx-snapshot-formula.cjs",
  staleAllowance: "services/market-intelligence/src/catalog-runtime-seed.cjs#LISTING_STALE_SEC",
  marketplaceMap: "services/market-intelligence/src/catalog-runtime-seed.cjs#MARKETPLACE_BY_MARKET",
  promotion: "services/market-intelligence/src/listing-promotion",
});

const EXECUTABLE_IS_NOT_OPPORTUNITY = true;
const DOES_NOT_CREATE_OPPORTUNITY = true;

module.exports = {
  EVALUATOR_VERSION,
  PIPELINE_STATUS,
  DECISIONS,
  REASONS,
  BOUNDARIES,
  FORMULA_OWNERS,
  EXECUTABLE_IS_NOT_OPPORTUNITY,
  DOES_NOT_CREATE_OPPORTUNITY,
};
